<?php

/**
 * @file
 * Module file for umdds_social_icons module.
 */

/**
 * Implements hook_theme().
 */
function umdds_social_icons_theme() {
  return [
    'umdds_social_icons' => [
      'variables' => [
        'icons' => '',
        'block_heading' => '',
        'all_accounts_link_text' => '',
        'all_accounts_link_url' => '',
        'standalone_page_content' => '',
      ],
    ],
    'umdds_social_icons_facebook' => [
      'variables' => [
        'url' => '',
      ],
    ],
    'umdds_social_icons_instagram' => [
      'variables' => [
        'url' => '',
      ],
    ],
    'umdds_social_icons_youtube' => [
      'variables' => [
        'url' => '',
      ],
    ],
    'umdds_social_icons_pinterest' => [
      'variables' => [
        'url' => '',
      ],
    ],
    'umdds_social_icons_tumblr' => [
      'variables' => [
        'url' => '',
      ],
    ],
    'umdds_social_icons_bluesky' => [
      'variables' => [
        'url' => '',
      ],
    ],
    'umdds_social_icons_wordpress' => [
      'variables' => [
        'url' => '',
      ],
    ],
    'umdds_social_icons_threads' => [
      'variables' => [
        'url' => '',
      ],
    ],
    'umdds_social_icons_mastodon' => [
      'variables' => [
        'url' => '',
      ],
    ],
    'umdds_social_icons_muskweb' => [
      'variables' => [
        'url' => '',
      ],
    ],
  ];
}
